-- ============================================================
-- Dimitri's Bakery CMS — Database Setup
-- Run this ONCE in cPanel phpMyAdmin against your database.
-- ============================================================

SET NAMES utf8mb4;
SET time_zone = '+02:00';

-- --------------------------------------------------------
-- Table: users
-- --------------------------------------------------------
CREATE TABLE IF NOT EXISTS `users` (
  `id`           INT UNSIGNED    NOT NULL AUTO_INCREMENT,
  `username`     VARCHAR(80)     NOT NULL UNIQUE,
  `password`     VARCHAR(255)    NOT NULL,
  `role`         ENUM('admin','user') NOT NULL DEFAULT 'user',
  `full_name`    VARCHAR(150)    DEFAULT NULL,
  `created_at`   TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- --------------------------------------------------------
-- Table: page_permissions
-- Defines which pages a user is allowed to manage.
-- Admin users bypass this table (they can manage everything).
-- --------------------------------------------------------
CREATE TABLE IF NOT EXISTS `page_permissions` (
  `id`        INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_id`   INT UNSIGNED NOT NULL,
  `page_slug` VARCHAR(60)  NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `user_page` (`user_id`, `page_slug`),
  CONSTRAINT `fk_perm_user` FOREIGN KEY (`user_id`) REFERENCES `users`(`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- --------------------------------------------------------
-- Table: photos
-- Tracks all CMS-managed photos.
-- --------------------------------------------------------
CREATE TABLE IF NOT EXISTS `photos` (
  `id`           INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `page_slug`    VARCHAR(60)  NOT NULL,
  `filename`     VARCHAR(255) NOT NULL,
  `caption`      VARCHAR(255) DEFAULT NULL,
  `uploaded_by`  INT UNSIGNED NOT NULL,
  `uploaded_at`  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_page_slug` (`page_slug`),
  CONSTRAINT `fk_photo_user` FOREIGN KEY (`uploaded_by`) REFERENCES `users`(`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- --------------------------------------------------------
-- Seed: Default admin account
-- Username: admin
-- Password: Admin@123  (CHANGE THIS immediately after first login!)
-- --------------------------------------------------------
INSERT INTO `users` (`username`, `password`, `role`, `full_name`)
VALUES (
  'admin',
  '$2y$12$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi',
  'admin',
  'Administrator'
);
-- NOTE: The hash above is for the password "Admin@123".
-- Replace it with your own hash generated by:
--   php -r "echo password_hash('YourPassword', PASSWORD_BCRYPT, ['cost'=>12]);"
